version: "3"
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: parking
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3307:3306
  elasticsearch_7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_7/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  elasticsearch_1:
    image: elasticsearch:1.7
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch_1/data:/usr/share/elasticsearch/data
      - ./elasticsearch_1/config:/usr/share/elasticsearch/config
    ports:
      - "9201:9200"
      - "9301:9300"
  mailhog:
    image: mailhog/mailhog
    restart: on-failure:5
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
