CREATE TABLE `ps_contact_log` (
  `c_id` int(11) NOT NULL AUTO_INCREMENT,
  `c_status` int(11) NOT NULL DEFAULT '0',
  `marketing_strategy` int(11) NOT NULL DEFAULT '0',
  `p_ids` varchar(255) NOT NULL,
  `personal_id` varchar(255) DEFAULT NULL,
  `user_class` int(11) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `user_name` varchar(255) DEFAULT NULL,
  `zip` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `mail` varchar(255) DEFAULT NULL,
  `tel` varchar(255) DEFAULT NULL,
  `tel2` varchar(255) DEFAULT NULL,
  `fax` varchar(255) DEFAULT NULL,
  `search_area` varchar(255) DEFAULT NULL,
  `search_lat` double NOT NULL DEFAULT '0',
  `search_lon` double NOT NULL DEFAULT '0',
  `search_min` int(11) DEFAULT NULL,
  `search_area_org` varchar(255) DEFAULT NULL,
  `search_min_org` int(11) DEFAULT NULL,
  `pref_code` int(2) NOT NULL DEFAULT '0',
  `city_code` int(5) NOT NULL DEFAULT '0',
  `region_code` int(9) NOT NULL DEFAULT '0',
  `car_model` varchar(255) DEFAULT NULL,
  `search_reason` int(11) DEFAULT NULL,
  `use_num` int(11) DEFAULT NULL,
  `use_timing` varchar(255) DEFAULT NULL,
  `comment` text,
  `memo` text,
  `concrete_schedule` date DEFAULT NULL,
  `maximun_of_budget` int(11) NOT NULL DEFAULT '0',
  `wish_of_roof` tinyint(1) NOT NULL DEFAULT '0',
  `priority_of_conditions` tinyint(1) NOT NULL DEFAULT '0',
  `is_moved` tinyint(1) NOT NULL DEFAULT '0',
  `building_has_parking` tinyint(1) NOT NULL DEFAULT '0',
  `is_bought` tinyint(1) NOT NULL DEFAULT '0',
  `car_is_decided` tinyint(1) NOT NULL DEFAULT '0',
  `necessity_of_certification` tinyint(1) NOT NULL DEFAULT '0',
  `c_mu_id` int(11) DEFAULT NULL,
  `c_datetime` datetime DEFAULT NULL,
  `c_update_datetime` datetime DEFAULT NULL,
  `c_same_id` int(11) DEFAULT NULL,
  `c_from_site` int(11) NOT NULL DEFAULT '-1',
  `c_passed_site` int(11) NOT NULL DEFAULT '0',
  `c_work_state` int(11) NOT NULL DEFAULT '0',
  `contact_contact_id` int(11) DEFAULT NULL,
  `car_model_id` int(11) DEFAULT NULL,
  `accepted_by` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`c_id`),
  KEY `idx1_ps_contact_log` (`c_status`,`search_lat`,`search_lon`),
  KEY `idx2_ps_contact_log` (`c_datetime`),
  KEY `idx3_ps_contact_log` (`accepted_by`),
  KEY `idx4_ps_contact_log` (`c_work_state`),
  KEY `idx5_ps_contact_log` (`c_same_id`),
  KEY `idx6_ps_contact_log` (`marketing_strategy`),
  KEY `idx7_ps_contact_log` (`car_model_id`),
  KEY `contact_log_status` (`c_status`),
  KEY `manager_id` (`c_mu_id`)
) ENGINE=InnoDB AUTO_INCREMENT=542596 DEFAULT CHARSET=utf8;

CREATE TABLE `user_email_setting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `notice_message_allowed` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_email_setting_email` (`email`),
  KEY `idx_user_email_setting_email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=125518 DEFAULT CHARSET=utf8;